App\Entity\OAuth\AccessToken:
  shortName: Oauth
  itemOperations: [ ]
  collectionOperations:
    oauth_token:
      method: POST
      route_name: oauth_token
      openapi_context:
        summary: "Generate authentication's access token with credential"
        description: "Generate authentication's access token with credential"
        requestBody:
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  grant_type:
                    type: string
                    description: "The grant type"
                    required: true
                    example: password
                  client_id:
                    type: string
                    description: "The client ID"
                    required: true
                  username:
                    type: string
                    description: "The user's email"
                    required: true
                  password:
                    type: string
                    description: "The user's password"
                    required: true
