App\Entity\OAuth\RefreshToken:
  shortName: Oauth
  itemOperations: [ ]
  collectionOperations:
    oauth_refresh:
      method: POST
      route_name: oauth_refresh
      openapi_context:
        summary: "Generate new authentication's access token with refresh token"
        description: "Generate new authentication's access token with refresh token"
        requestBody:
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  grant_type:
                    type: string
                    description: "The grant type"
                    required: true
                    example: refresh_token
                  client_id:
                    type: string
                    description: "The client ID"
                    required: true
                  refresh_token:
                    type: string
                    description: "The refresh token"
                    required: true
