services:
  app.block.flash:
    class: App\Service\Block\MessageFlashBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }

  app.block.topbar:
    class: App\Service\Block\TopbarBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }

  app.block.searchbar:
    class: App\Service\Block\SearchbarBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }

  app.block.card.account:
    class: App\Service\Block\AccountCardBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }

  app.block.table.transfers:
    class: App\Service\Block\TransfersTableBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }

  app.block.table.livingWage:
    class: App\Service\Block\LivingWageTableBlock
    arguments: ['@twig']
    tags:
      - { name: sonata.block }
